# Generated by Django 5.0.2 on 2024-03-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoices",
            name="cost",
            field=models.FloatField(verbose_name="Koszt z faktury"),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="cost_per_1_mwh",
            field=models.FloatField(verbose_name="Koszt za 1 MWH"),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="energysuppliers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="electricity_cost.energysuppliers",
                verbose_name="Dostawca",
            ),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="invoices_number",
            field=models.FloatField(verbose_name="Numer faktury"),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="numbers_mwh",
            field=models.FloatField(verbose_name="Ilość zużytych MWH"),
        ),
    ]
