# Generated by Django 5.0.2 on 2024-03-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0003_energymeters_institute_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energymeters",
            name="institute_share",
            field=models.FloatField(),
        ),
    ]
