# Generated by Django 5.0.2 on 2024-03-03 21:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0004_alter_energymeters_institute_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="energymeters",
            name="technical_name",
            field=models.TextField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="Nazwa licznika z BMS",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="cob_share",
            field=models.FloatField(default=0, verbose_name="Udział COB"),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="institute_share",
            field=models.FloatField(default=0, verbose_name="Udział Instytutu"),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="meter_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="electricity_cost.meterlocations",
                verbose_name="Lokalizacja licznika",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="museum_share",
            field=models.FloatField(default=0, verbose_name="Udział Muzeum"),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="name",
            field=models.TextField(max_length=200, verbose_name="Nazwa licznika"),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="parish_share",
            field=models.FloatField(default=0, verbose_name="Udział Parafii"),
        ),
    ]
