# Generated by Django 5.0.2 on 2024-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0005_energymeters_technical_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="month",
            field=models.IntegerField(default=1, verbose_name="Miesiąc zużycia"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoices",
            name="year",
            field=models.IntegerField(default=1, verbose_name="Rok zużycia"),
            preserve_default=False,
        ),
    ]
