# Generated by Django 5.0.2 on 2024-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0006_invoices_month_invoices_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterShares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
            ],
        ),
        migrations.RemoveField(model_name="energymeters", name="cob_share",),
        migrations.RemoveField(model_name="energymeters", name="institute_share",),
        migrations.RemoveField(model_name="energymeters", name="museum_share",),
        migrations.RemoveField(model_name="energymeters", name="parish_share",),
    ]
