# Generated by Django 5.0.2 on 2024-03-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0007_metershares_remove_energymeters_cob_share_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energymeters",
            name="cob_share",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cob_share",
                to="electricity_cost.metershares",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energymeters",
            name="institute_share",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_share",
                to="electricity_cost.metershares",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energymeters",
            name="museum_share",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="museum_share",
                to="electricity_cost.metershares",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energymeters",
            name="parish_share",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parish_share",
                to="electricity_cost.metershares",
            ),
            preserve_default=False,
        ),
    ]
