# Generated by Django 5.0.2 on 2024-03-08 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "electricity_cost",
            "0008_energymeters_cob_share_energymeters_institute_share_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="energymeters",
            name="cob_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cob_share",
                to="electricity_cost.metershares",
                verbose_name="Udział COB",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="institute_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institute_share",
                to="electricity_cost.metershares",
                verbose_name="Udział Instytutu",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="museum_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="museum_share",
                to="electricity_cost.metershares",
                verbose_name="Udział Muzeum",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="parish_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parish_share",
                to="electricity_cost.metershares",
                verbose_name="Udział Parafii",
            ),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="invoices_number",
            field=models.TextField(verbose_name="Numer faktury"),
        ),
    ]
