# Generated by Django 5.0.2 on 2024-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0009_alter_energymeters_cob_share_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Nazwa podmiotu"),
                ),
            ],
        ),
    ]
