# Generated by Django 5.0.2 on 2024-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0010_financialentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energymeters",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nazwa licznika"),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="technical_name",
            field=models.CharField(max_length=200, verbose_name="Nazwa licznika z BMS"),
        ),
        migrations.AlterField(
            model_name="energysuppliers",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="invoices_number",
            field=models.CharField(max_length=250, verbose_name="Numer faktury"),
        ),
        migrations.AlterField(
            model_name="meterlocations",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
