# Generated by Django 5.0.2 on 2024-03-09 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0011_alter_energymeters_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoices", name="month",),
        migrations.RemoveField(model_name="invoices", name="year",),
        migrations.AddField(
            model_name="invoices",
            name="biling_month",
            field=models.IntegerField(default=1, verbose_name="Miesiąc rozliczeniowy"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoices",
            name="biling_year",
            field=models.IntegerField(default=2024, verbose_name="Rok rozliczeniowy"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month_of_reading",
                    models.IntegerField(verbose_name="Miesiac rozliczeniowy"),
                ),
                (
                    "year_of_reading",
                    models.IntegerField(verbose_name="Rok rozliczeniowy"),
                ),
                ("date_of_reading", models.DateField(verbose_name="Data odczytu")),
                ("meter_reading", models.FloatField(verbose_name="Odczyt licznika")),
                (
                    "biling_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Miesiąc rozliczeniowy",
                    ),
                ),
                (
                    "biling_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2024),
                            django.core.validators.MaxValueValidator(2024),
                        ],
                        verbose_name="Rok rozliczeniowy",
                    ),
                ),
                (
                    "energy_meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electricity_cost.energymeters",
                        verbose_name="Licznik",
                    ),
                ),
            ],
        ),
    ]
