# Generated by Django 5.0.2 on 2024-03-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "electricity_cost",
            "0012_remove_invoices_month_remove_invoices_year_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="meterreading", name="month_of_reading",),
        migrations.RemoveField(model_name="meterreading", name="year_of_reading",),
    ]
