# Generated by Django 5.0.2 on 2024-03-09 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0013_remove_meterreading_month_of_reading_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Miesiąc")),
                ("number_of_month", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Rok")),
            ],
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="cob_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cob_share",
                to="electricity_cost.metershares",
                verbose_name="Udział COB",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="institute_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institute_share",
                to="electricity_cost.metershares",
                verbose_name="Udział Instytutu",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="meter_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.meterlocations",
                verbose_name="Lokalizacja licznika",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="museum_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="museum_share",
                to="electricity_cost.metershares",
                verbose_name="Udział Muzeum",
            ),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="parish_share",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parish_share",
                to="electricity_cost.metershares",
                verbose_name="Udział Parafii",
            ),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="energysuppliers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.energysuppliers",
                verbose_name="Dostawca",
            ),
        ),
        migrations.AlterField(
            model_name="meterreading",
            name="biling_month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.month",
                verbose_name="Miesiąc rozliczeniowy",
            ),
        ),
        migrations.AlterField(
            model_name="meterreading",
            name="biling_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.year",
                verbose_name="Rok rozliczeniowy",
            ),
        ),
    ]
