# Generated by Django 5.0.2 on 2024-03-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0014_month_year_alter_energymeters_cob_share_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoices",
            name="biling_month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.month",
                verbose_name="Miesiąc rozliczeniowy",
            ),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="biling_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.year",
                verbose_name="Rok rozliczeniowy",
            ),
        ),
    ]
