# Generated by Django 5.0.2 on 2024-03-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0015_alter_invoices_biling_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meterreading",
            name="energy_meter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.energymeters",
                verbose_name="Licznik",
            ),
        ),
        migrations.CreateModel(
            name="CounterUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage", models.FloatField(verbose_name="Zużycie licznika")),
                (
                    "biling_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electricity_cost.month",
                        verbose_name="Miesiąc rozliczeniowy",
                    ),
                ),
                (
                    "biling_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electricity_cost.year",
                        verbose_name="Rok rozliczeniowy",
                    ),
                ),
                (
                    "energy_meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electricity_cost.energymeters",
                        verbose_name="Licznik",
                    ),
                ),
            ],
        ),
    ]
