# Generated by Django 5.0.2 on 2024-03-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0016_alter_meterreading_energy_meter_counterusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyMeterTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "energy_meter_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="energy_meter_main",
                        to="electricity_cost.energymeters",
                        verbose_name="Licznik nadrzędny",
                    ),
                ),
                (
                    "energy_meter_submain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="energy_meter_submain",
                        to="electricity_cost.energymeters",
                        verbose_name="Licznik poddrzędny",
                    ),
                ),
            ],
        ),
    ]
