# Generated by Django 5.0.2 on 2024-03-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0017_energymetertree"),
    ]

    operations = [
        migrations.RemoveField(model_name="counterusage", name="biling_month",),
        migrations.RemoveField(model_name="counterusage", name="biling_year",),
        migrations.CreateModel(
            name="MeterReadingsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_reading_name",
                    models.CharField(max_length=100, verbose_name="Nazwa odczytu"),
                ),
                (
                    "biling_month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electricity_cost.month",
                        verbose_name="Miesiąc rozliczeniowy",
                    ),
                ),
                (
                    "biling_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="electricity_cost.year",
                        verbose_name="Rok rozliczeniowy",
                    ),
                ),
            ],
        ),
    ]
