# Generated by Django 5.0.2 on 2024-03-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0019_remove_meterreading_biling_month_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meterreadingslist", unique_together={("biling_month", "biling_year")},
        ),
    ]
