# Generated by Django 5.0.2 on 2024-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0020_alter_meterreadingslist_unique_together"),
    ]

    operations = [
        migrations.RemoveField(model_name="meterreading", name="date_of_reading",),
        migrations.AddField(
            model_name="meterreadingslist",
            name="date_of_read",
            field=models.DateField(default="2023-01-01", verbose_name="Data odczytu"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meterreadingslist",
            name="photo",
            field=models.FileField(
                default="test",
                upload_to="files/%Y/%m/%d",
                verbose_name="Zdjecie licznika",
            ),
            preserve_default=False,
        ),
    ]
