# Generated by Django 5.0.2 on 2024-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0021_remove_meterreading_date_of_reading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meterreadingslist", name="meter_reading_name",
        ),
        migrations.AddField(
            model_name="meterreadingslist",
            name="add_automatic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meterreadingslist",
            name="add_manualy",
            field=models.BooleanField(default=False),
        ),
    ]
