# Generated by Django 5.0.2 on 2024-04-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "electricity_cost",
            "0022_remove_meterreadingslist_meter_reading_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="energymeters",
            name="is_add_manual",
            field=models.BooleanField(
                default=False, verbose_name="Licznik dodawany ręcznie"
            ),
        ),
    ]
