# Generated by Django 5.0.2 on 2024-04-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0032_alter_meterreadingslist_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meterreadingslist",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/%Y/%m/%d",
                verbose_name="Zdjecie licznika",
            ),
        ),
        migrations.AlterField(
            model_name="meterreadingslist",
            name="xlsx_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files_xlsx/%Y/%m/%d",
                verbose_name="Dane z odczytu automatycznego",
            ),
        ),
    ]
