# Generated by Django 5.0.2 on 2024-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0034_remove_counterusage_biling_month_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOfInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
    ]
