# Generated by Django 5.0.2 on 2024-07-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0035_typeofinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="type_of_invoice",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.typeofinvoice",
                verbose_name="Typ faktury",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="typeofinvoice",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Typ faktury"),
        ),
    ]
