# Generated by Django 5.0.2 on 2024-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0037_energymeters_conversion_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="energymeters",
            name="is_virtual",
            field=models.BooleanField(default=False, verbose_name="Czy wirtualny"),
        ),
        migrations.AlterField(
            model_name="energymeters",
            name="conversion_factor",
            field=models.FloatField(default=1.0, verbose_name="Przelicznik"),
        ),
        migrations.AlterUniqueTogether(
            name="invoices",
            unique_together={("biling_month", "biling_year", "type_of_invoice")},
        ),
    ]
