# Generated by Django 5.0.2 on 2024-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0038_energymeters_is_virtual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="counterusage",
            name="usage_cob",
            field=models.FloatField(default=0, verbose_name="Zużycie COB"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counterusage",
            name="usage_institute",
            field=models.FloatField(default=0, verbose_name="Zużycie instytutu"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counterusage",
            name="usage_museum",
            field=models.FloatField(default=0, verbose_name="Zużycie muzeum"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="counterusage",
            name="usage_parish",
            field=models.FloatField(default=0, verbose_name="Zużycie parafii"),
            preserve_default=False,
        ),
    ]
