# Generated by Django 5.0.2 on 2024-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "electricity_cost",
            "0039_counterusage_usage_cob_counterusage_usage_institute_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="meterreadingslist",
            name="date_of_read",
            field=models.DateField(blank=True, null=True, verbose_name="Data odczytu"),
        ),
    ]
