# Generated by Django 5.0.2 on 2024-10-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0041_alter_invoices_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energymeters",
            name="initial_value",
            field=models.FloatField(default=0, verbose_name="Licznik z BMS"),
        ),
    ]
