# Generated by Django 5.0.2 on 2024-11-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0043_vatrate_alter_energymeters_initial_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="vat_rate",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="electricity_cost.vatrate",
                verbose_name="Stawka Vat",
            ),
            preserve_default=False,
        ),
    ]
