# Generated by Django 5.0.2 on 2024-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity_cost", "0045_alter_invoices_vat_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeterReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("energy_meter", models.FloatField(verbose_name="Licznik")),
                ("meter_reading", models.FloatField(verbose_name="Odczyt licznika")),
                ("reading_name", models.FloatField(verbose_name="Lista licznika")),
                ("user", models.CharField(verbose_name="Nazwa użytkownika")),
                ("data_of_changed", models.DateField(verbose_name="Data zmiany")),
            ],
        ),
    ]
