import streamlit as st
import graphviz

graph = graphviz.Digraph()

graph.attr(rankdir='LR')

graph.edge('Licznik główny obiektu', 'S1/QG1 SN:')
graph.edge('Licznik główny obiektu', 'S1/QG2 SN:')
graph.edge('Licznik główny obiektu', 'S1/QG3 SN:')
graph.edge('Licznik główny obiektu', 'S2/QG1 SN:')
graph.edge('Licznik główny obiektu', 'S2/QG2 SN:')
graph.edge('Licznik główny obiektu', 'S3/QG1 SN:')
graph.edge('Licznik główny obiektu', 'S3/QG2 SN:')
graph.edge('Licznik główny obiektu', 'S4/QG1 SN:')
graph.edge('Licznik główny obiektu', 'S4/QG2 SN:')
graph.edge('S1/QG1 SN:', 'S1/LQ01 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ02 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ03 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ04 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ05 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ06 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ07 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ08 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ09 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ10 SN')
graph.edge('S1/QG1 SN:', 'S1/LQ11 SN')
graph.edge('S2/QG1 SN:', 'S2/LQ1 SN:')
graph.edge('S2/QG1 SN:', 'S2/LQ2 SN:')
graph.edge('S2/QG1 SN:', 'S2/LQ3 SN:')
graph.edge('S2/QG1 SN:', 'S2/LQ4 SN:')
graph.edge('S2/QG1 SN:', 'S2/LQ5 SN:')
graph.edge('S2/QG1 SN:', 'S2/LQ6 SN:')
graph.edge('S2/QG1 SN:', 'S2/LQ7 SN:')
graph.edge('S2/QG1 SN:', 'S2/RW1 SN:')
graph.edge('S2/QG1 SN:', 'S2/RW2 SN:')
graph.edge('S2/QG1 SN:', 'S2/RW3 SN:')
graph.edge('S2/QG1 SN:', 'S2/RW4 SN:')
graph.edge('S4/QG1 SN:', 'S4/LQ01 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ02 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ03 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ04 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ05 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ06 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ07 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ08 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ09 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ10 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ11 SN')
graph.edge('S4/QG1 SN:', 'S4/LQ12 SN')
graph.edge('Wirtualny licznik instytutu', 'Mieszkania klatka A')
graph.edge('Wirtualny licznik instytutu', 'Korytarz klatka A')
graph.edge('Wirtualny licznik instytutu', 'Mieszkania')
graph.edge('Wirtualny licznik instytutu', 'Korytarz klatka B')
graph.edge('Wirtualny licznik instytutu', 'Mieszkania')
graph.edge('Wirtualny licznik instytutu', 'Korytarz')
graph.edge('Wirtualny licznik instytutu', 'Mieszkania')
graph.edge('Wirtualny licznik instytutu', 'Korytarz')
graph.edge('Wirtualny licznik instytutu', 'Korytarz - klatka B')
graph.edge('Wirtualny licznik instytutu', 'Korytarz - klatka A')
graph.edge('Wirtualny licznik instytutu', 'Serwerownia')
graph.edge('Wirtualny licznik instytutu', 'Kuchnia zaplecze')
graph.edge('Wirtualny licznik instytutu', 'Kuchnia zaplecze')
graph.edge('Wirtualny licznik instytutu', 'Winda 1 - klatka A')
graph.edge('Wirtualny licznik instytutu', 'Winda 2 - klatka B')
graph.edge('Wirtualny licznik instytutu', 'Garaż poziom -1')
graph.edge('Wirtualny licznik instytutu', 'Wentylatornia')
graph.edge('Wirtualny licznik instytutu', 'Hydrofornia')
graph.edge('Wirtualny licznik instytutu', 'Garaż poziom -1')
graph.edge('Licznik główny obiektu', 'Wirtualny licznik instytutu')
graph.edge(	 'S3/QG1 SN:'	,	 'RG/LQ10 SN'	)
graph.edge(	 'S1/QG1 SN:'	,	 'RG/LQ9 SN:'	)
graph.edge(	 'S2/QG1 SN:'	,	 'RG/AP1 SN:'	)
graph.edge(	 'S4/QG1 SN:'	,	 'RG/AP2 SN:'	)

st.graphviz_chart(graph)
